services:
  app:
    profiles:
      - dev
    build: .
    container_name: app-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

  db:
    profiles:
      - dev
    image: postgres:17-alpine
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
    restart: unless-stopped

volumes:
  db-data:

networks:
  backend:
    driver: bridge
