"""del unique_constraint from products_barcodes.barcode

Revision ID: 9351ffb203e6
Revises: 92ecdff84642
Create Date: 2025-08-20 10:29:21.153500

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9351ffb203e6"
down_revision: str | Sequence[str] | None = "92ecdff84642"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("product_barcodes_barcode_key"), "product_barcodes", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("product_barcodes_barcode_key"),
        "product_barcodes",
        ["barcode"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
