"""create tables products

Revision ID: 92ecdff84642
Revises:
Create Date: 2025-08-20 09:14:04.394940

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92ecdff84642"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("article", sa.String(length=100), nullable=True),
        sa.Column("base_unit", sa.String(length=20), nullable=False),
        sa.Column("main_unit", sa.String(length=20), nullable=False),
        sa.Column("full_name", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "product_barcodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_code", sa.String(length=20), nullable=False),
        sa.Column("barcode", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_code"],
            ["products.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("barcode"),
    )
    op.create_table(
        "product_descriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_code", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("main_property", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_code"],
            ["products.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_dimensions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_code", sa.String(length=20), nullable=False),
        sa.Column("length", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("width", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("height", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("volume", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_code"],
            ["products.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_online",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_code", sa.String(length=20), nullable=False),
        sa.Column("export_to_online_store", sa.Boolean(), nullable=False),
        sa.Column("online_store_name", sa.String(length=500), nullable=True),
        sa.Column("block_discount", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_code"],
            ["products.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_stocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_code", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("max_purchase", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_code"],
            ["products.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("opt_card", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("opt_card_plus", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("opt", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("retail", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("gold", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("platinum", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["code"],
            ["products.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_prices_code"), "products_prices", ["code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_prices_code"), table_name="products_prices")
    op.drop_table("products_prices")
    op.drop_table("product_stocks")
    op.drop_table("product_online")
    op.drop_table("product_dimensions")
    op.drop_table("product_descriptions")
    op.drop_table("product_barcodes")
    op.drop_table("products")
    # ### end Alembic commands ###
