"""change unique_constraint in all tables Product in product_code

Revision ID: 6ebdf236b72e
Revises: 9351ffb203e6
Create Date: 2025-08-20 12:05:03.855337

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ebdf236b72e"
down_revision: str | Sequence[str] | None = "9351ffb203e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_product_descriptions_product_code"),
        "product_descriptions",
        ["product_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_product_dimensions_product_code"),
        "product_dimensions",
        ["product_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_product_online_product_code"),
        "product_online",
        ["product_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_product_stocks_product_code"),
        "product_stocks",
        ["product_code"],
        unique=True,
    )
    op.create_unique_constraint(None, "products", ["code"])
    op.add_column(
        "products_prices",
        sa.Column("product_code", sa.String(length=20), nullable=False),
    )
    op.drop_index(op.f("ix_products_prices_code"), table_name="products_prices")
    op.create_index(
        op.f("ix_products_prices_product_code"),
        "products_prices",
        ["product_code"],
        unique=True,
    )
    op.drop_constraint(
        op.f("products_prices_code_fkey"), "products_prices", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "products_prices", "products", ["product_code"], ["code"]
    )
    op.drop_column("products_prices", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products_prices",
        sa.Column("code", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "products_prices", type_="foreignkey")
    op.create_foreign_key(
        op.f("products_prices_code_fkey"),
        "products_prices",
        "products",
        ["code"],
        ["code"],
    )
    op.drop_index(op.f("ix_products_prices_product_code"), table_name="products_prices")
    op.create_index(
        op.f("ix_products_prices_code"), "products_prices", ["code"], unique=True
    )
    op.drop_column("products_prices", "product_code")
    op.drop_constraint(None, "products", type_="unique")
    op.drop_index(op.f("ix_product_stocks_product_code"), table_name="product_stocks")
    op.drop_index(op.f("ix_product_online_product_code"), table_name="product_online")
    op.drop_index(
        op.f("ix_product_dimensions_product_code"), table_name="product_dimensions"
    )
    op.drop_index(
        op.f("ix_product_descriptions_product_code"), table_name="product_descriptions"
    )
    # ### end Alembic commands ###
