"""remove unique index from product_barcodes.barcode

Revision ID: c2dc597f71f0
Revises: 26cb74def952
Create Date: 2025-08-20 14:14:15.491812

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2dc597f71f0"
down_revision: str | Sequence[str] | None = "26cb74def952"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_product_barcodes_barcode"), "product_barcodes", type_="unique"
    )
    op.create_unique_constraint(op.f("uq_products_code"), "products", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_products_code"), "products", type_="unique")
    op.create_unique_constraint(
        op.f("uq_product_barcodes_barcode"),
        "product_barcodes",
        ["barcode"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
