"""add null to all types of prices in products_prices

Revision ID: c34a81e11a86
Revises: c2dc597f71f0
Create Date: 2025-08-20 14:54:52.062170

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c34a81e11a86"
down_revision: str | Sequence[str] | None = "c2dc597f71f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products_prices",
        "opt_card",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "products_prices",
        "opt_card_plus",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "products_prices",
        "opt",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "products_prices",
        "retail",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "products_prices",
        "gold",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column(
        "products_prices",
        "platinum",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products_prices",
        "platinum",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "products_prices",
        "gold",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "products_prices",
        "retail",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "products_prices",
        "opt",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "products_prices",
        "opt_card_plus",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "products_prices",
        "opt_card",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###
